# Generated by Django 4.2.10 on 2026-03-16 05:18

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def bootstrap_email_verification_defaults(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    SiteSettings = apps.get_model("accounts", "SiteSettings")

    User.objects.filter(email_verified=False).update(email_verified=True)
    SiteSettings.objects.update_or_create(
        pk=1,
        defaults={
            "require_email_verification": True,
            "logged_in_users_only_default": False,
            "ai_provider": "openai",
            "ai_api_key_openai": "",
            "ai_api_key_anthropic": "",
        },
    )


def rollback_email_verification_defaults(apps, schema_editor):
    SiteSettings = apps.get_model("accounts", "SiteSettings")
    SiteSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_designation_user_organization_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("require_email_verification", models.BooleanField(default=True)),
                ("logged_in_users_only_default", models.BooleanField(default=False)),
                (
                    "ai_provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        default="openai",
                        max_length=20,
                    ),
                ),
                (
                    "ai_api_key_openai",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "ai_api_key_anthropic",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=accounts.models.generate_email_verification_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=accounts.models.get_default_verification_expiry
                    ),
                ),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="accounts_em_user_id_6989e4_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_em_expires_f36bd3_idx"
                    ),
                ],
            },
        ),
        migrations.RunPython(
            bootstrap_email_verification_defaults,
            rollback_email_verification_defaults,
        ),
    ]
