# Generated by Django 4.2.10 on 2026-03-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_sitesettings_user_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ai_model_anthropic",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_model_openai",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
