# Generated by Django 4.2.10 on 2026-03-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_sitesettings_ai_model_anthropic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="ai_api_key_anthropic",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="ai_api_key_openai",
        ),
    ]

