import {
  AlignLeft,
  ArrowDownUp,
  CalendarClock,
  CircleHelp,
  Heading2,
  ImagePlus,
  ListChecks,
  ListFilter,
  ListTodo,
  Mail,
  MessageSquareText,
  MousePointerSquareDashed,
  PanelTop,
  Rows3,
  Scale,
  SlidersHorizontal,
  Star,
  Table2,
  Upload,
} from 'lucide-react'

export const QUESTION_TYPE_ICONS = {
  multiple_choice_single: CircleHelp,
  multiple_choice_multi: ListChecks,
  dropdown: ListFilter,
  short_text: AlignLeft,
  open_ended: Rows3,
  long_text: MessageSquareText,
  yes_no: MousePointerSquareDashed,
  rating_scale: SlidersHorizontal,
  star_rating: Star,
  nps: Scale,
  constant_sum: ArrowDownUp,
  date_time: CalendarClock,
  matrix: Table2,
  matrix_plus: Table2,
  ranking: ListTodo,
  image_choice: ImagePlus,
  file_upload: Upload,
  demographics: Mail,
  section_heading: Heading2,
  instructional_text: PanelTop,
}
