# Generated by Django 4.2.10 on 2026-03-18 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveys", "0003_expand_question_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="survey_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
